// Generated by CoffeeScript 1.8.0
(function() {
  var AppAction;

  AppAction = (function() {
    var DomainCtrl;

    function AppAction() {}

    DomainCtrl = require("./../control/domainCtrl");

    AppAction.getDomain = function(req, res, next) {
      var domain;
      domain = "www.meitrip.net";
      return DomainCtrl.getEnt(domain, function(err, result) {
        if (err != null) {
          return res.redirect("404");
        } else {
          res.locals.domain = result;
          return next();
        }
      });
    };

    return AppAction;

  })();

  module.exports = AppAction;

}).call(this);
